apiVersion: v1
kind: ConfigMap

metadata:
  name: flask-config
  namespace: infraready

data:
  APP_ENV: "production"
  APP_VERSION: "3.0"
  PORT: "5000"

  DB_HOST: "postgres-service"
  DB_NAME: "infradb"
  DB_USER: "infrauser"
